#!/usr/bin/perl
#======================================================================
#                    C P X 
#                    doc: Sat Feb  1 11:43:16 2020
#                    dlm: Sun Feb  2 20:34:56 2020
#                    (c) 2020 A.M. Thurnherr
#                    uE-Info: 16 41 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# translate cmp -l input to hex

while (<>) {
	chomp;
	@V = split; 
	die("@_") unless (@V == 3);
	printf("%04X: %02X -> %02X\n",$V[0]-1,oct($V[1]),oct($V[2]));
}

exit(0);
