#!/usr/bin/perl
#======================================================================
#					 D I S A S S E M B L E _ W P C _ D M D 
#					 doc: Thu Jul 18 06:30:12 2024
#					 dlm: Sat Jul 20 02:54:39 2024
#					 (c) 2024 idealjoker@mailbox.org
#					 uE-Info: 61 0 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# WMS WPC Game Disassembly Instructions

# HISTORY:
#	Jul 18, 2024: - created in Zermatt

use lib ($0 =~ m@/[^/]*$@,$`);												# load [D711.pm]
use D711 ('WPC_DMD');		

#----------------------------------------------------------------------
# Usage
#----------------------------------------------------------------------

use Getopt::Std;

die("Usage:\t$0\n\t\t[dump -l)abels] [-u)se <label-file>]\n\t\t" .
			"[write code-structuring -h)ints to <file>]\n\t\t" .
			"[-i)nclude <file[,...]>\n\t\t" .
			"[list -a)ddressse in output] [list -c)ode bytes]\n\t\t" . 
			"[suppress -g)ap data]\n\t\t" . 
			"[suppress code-s)tructure analysis]\n\t\t" .
			"<ROM image>\n")
	unless &getopts('acgh:i:ls') && @ARGV==1;

$D711::print_addrs	=  $opt_a;												# -a) include hex addresses in output
$D711::print_code	=  $opt_c;												# -c) include code bytes in output
$D711::fill_gaps	= !$opt_g;

if (defined($opt_i)) {														# include files with perl code
	my(@linc) = split(',',$opt_i);
	while (@linc) {
		require './' . shift(@linc);
	}	
}

#----------------------------------------------------------------------
# Load ROM Image
#----------------------------------------------------------------------

&D711::load_ROM($ARGV[0],0x8000,480,32);
printf(STDERR "[Address range = %04X-%04X]\n",$D711::MIN_ROM_ADDR,$D711::MAX_ROM_ADDR);

#----------------------------------------------------------------------
# Code Disassembly
#----------------------------------------------------------------------

&D711::disassemble_WPC_DMD();

#----------------------------------------------------------------------
# Make Human Readable
#----------------------------------------------------------------------

&D711::process_code_structure($D711::MIN_ROM_ADDR,$D711::MAX_ROM_ADDR) 		# if, while, ...
	unless ($opt_s);
&D711::substitute_labels(); 												# resolve labels
&D711::substitute_identifiers();											# rename game-specific ids

&D711::apply_magic_WPC_DMD();												# e.g. ScoreByte

#----------------------------------------------------------------------
# Produce Output
#----------------------------------------------------------------------

if ($opt_l) {																# dump label information
	&D711::dump_labels(1);													# fmt == 1 generates code that can be used with -u
	exit(0);																# to make a disassembled file with all labels defined up-front
}

if (defined($opt_h)) {														# find structure-breaking labels and create file with hints
	close(STDOUT);															# suppress code output
	&D711::produce_output($opt_h);
	exit(0);
}

&D711::produce_output(); 													# include API in output (has to be for compilation)

exit(0);

#======================================================================
# Utilities
#======================================================================

sub defSwitch($$)
{
	my($no,$name) = @_;

	die("defSwitch: invalid switch number $no\n")
		unless ($no>=1 && $no<65);
	$D711::Switch[$no-1] = $name;
}

sub defLamp($$$)
{
	my($row,$col,$name) = @_;

	die("defLamp: invalid lamp row number $row\n")
		unless ($row>=1 && $row<=8);
	die("defLamp: invalid lamp column number $row\n")
		unless ($col>=1 && $col<=8);
	$D711::Lamp[8*($col-1)+$row-1] = $name;
}


