#!/usr/bin/perl
#======================================================================
#                    M K I N D E X 
#                    doc: Wed Sep 29 19:38:02 2021
#                    dlm: Mon May 27 21:29:39 2024
#                    (c) 2021 idealjoker@mailbox.org
#                    uE-Info: 6 52 NIL 0 0 72 2 2 4 NIL ofnI
#======================================================================

# HISTORY:
#	Sep 29, 2021: - created
#	May 27, 2024: - made work with disassembled code containg addresses

my($in_header) = 0;

while (<>) {
	$in_header = 0,next unless /^(<[0-9A-F]{4}>\t)?;/;
	if ($in_header) {
		print;
		$in_header = 0 if /[-=]{5}/;
	} else {
		$in_header = 1,print if /[-=]{5}/;
	}
}

exit(0);
