#!/usr/bin/perl
#======================================================================
#                    R E N D E R _ C H A R 
#                    doc: Tue Sep 28 07:33:39 2021
#                    dlm: Mon May 27 21:29:40 2024
#                    (c) 2021 idealjoker@mailbox.org
#                    uE-Info: 6 52 NIL 0 0 72 0 2 4 NIL ofnI
#======================================================================

die("Usage: $0 <hex>\n")
	unless ($#ARGV == 0);

$val = hex($ARGV[0]);

print(($val & 0x0100) ? " ------- \n" : "         \n");

print(($val & 0x2000) ? "|" : " ");
print(($val & 0x0001) ? "\\" : " ");
print(($val & 0x0002) ? "  |  " : "     ");
print(($val & 0x0004) ? "/" : " ");
print(($val & 0x0200) ? "|\n" : " \n");

print(($val & 0x2000) ? "|" : " ");
print(($val & 0x0001) ? " \\" : "  ");
print(($val & 0x0002) ? " | " : "   ");
print(($val & 0x0004) ? "/ " : "  ");
print(($val & 0x0200) ? "|\n" : "  \n");

print(($val & 0x4000) ? " --- " : "     ");
print(($val & 0x0008) ? "--- \n" : "    \n");

print(($val & 0x1000) ? "|" : " ");
print(($val & 0x0040) ? " /" : "  ");
print(($val & 0x0020) ? " | " : "   ");
print(($val & 0x0010) ? "\\ " : "  ");
print(($val & 0x0400) ? "|\n" : "  \n");

print(($val & 0x1000) ? "|" : " ");
print(($val & 0x0040) ? "/" : " ");
print(($val & 0x0020) ? "  |  " : "     ");
print(($val & 0x0010) ? "\\" : " ");
print(($val & 0x0400) ? "|\n" : " \n");

print(($val & 0x0800) ? " ------- \n" : "         \n");

exit(0);
